name       : qt6-positioning
version    : 6.3.0
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtpositioning-everywhere-src-6.3.0.tar.xz : e9ed50f6b245a346db34d625d0012774ef0ec8e7fd65037127ec26758708236e
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 position, satellite and area monitoring classes
description: |
    Provides access to position, satellite and area monitoring classes
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6SerialPort)
    - pkgconfig(gconf-2.0)
rundeps    :
    - devel :
        - gconf-devel
replaces   :
    - qt6-location
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt6/bin
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
