name       : qt6-positioning
version    : 6.5.1
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.5/6.5.1/submodules/qtpositioning-everywhere-src-6.5.1.tar.xz : 053cf940e18880c53ec35022d495c75fdb3adf762dbb3b4a6e48341f7a0ea422
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 position, satellite and area monitoring classes
description: |
    Provides access to position, satellite and area monitoring classes
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6SerialPort)
    - pkgconfig(gconf-2.0)
rundeps    :
    - devel :
        - gconf-devel
replaces   :
    - qt6-location
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt6/bin
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
