name       : qt6-positioning
version    : 6.2.2
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtpositioning-everywhere-src-6.2.2.tar.xz : 26231545eae383089510b236e88bbee8a6d338c06c170b674e8f36a57a0ba09a
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 position, satellite and area monitoring classes
description: |
    Provides access to position, satellite and area monitoring classes
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6SerialPort)
    - pkgconfig(gconf-2.0)
rundeps    :
    - devel :
        - gconf-devel
replaces   :
    - qt6-location
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt6/bin
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
